name: Deploy Theme Dev
on:
  push:
    branches:
      - simply-keep-dev
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update INQUIRYHOOKURL
        run: perl -pi -e 's/INQUIRYHOOKURL/"$ENV{INQUIRYHOOK}"/' assets/scripts/itk.js
        env:
          INQUIRYHOOK: ${{ secrets.INQUIRYHOOK }}
      - name: Deploy Ghost Theme Dev
        uses: TryGhost/action-deploy-theme@v1.4.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL_DEV }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY_DEV }}
          theme-name: simply-keep-dev

## Configuration

## The `with` portion of the workflow **must** be configured before the action will work. Any `secrets` must be referenced using the bracket syntax and stored in the GitHub repositories `Settings/Secrets` menu. You can learn more about setting environment variables with GitHub actions [here](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsenv).

## | Key  | Value Information | Type | Required |
## | ------------- | ------------- | ------------- | ------------- |
## | `api-url`  | The base URL of your Ghost Admin API, found by configuring a new Custom Integration in Ghost Admin&raquo;Integrations | `secrets` | **Yes** |
## | `api-key`  | The authentication key for your Ghost Admin API, found by configuring a new Custom Integration in Ghost Admin&raquo;Integrations | `secrets` | **Yes** |
## | `exclude` | A list of files & folders to exclude from the generated zip file in addition to the defaults, e.g. `"gulpfile.js *dist/*"` | `string` | No |
## | `theme-name` | A custom theme name that overrides the default name in package.json. Useful if you use a fork of Casper, e.g. `"my-theme"` | `string` | No |
## | `file` | Path to a built zip file. If this is included, the `exclude` and `theme-name` options are ignored | `string` | No |
